pandemic:
  collision_detection: 'quadtree'  # basic or selective or quadtree
  at_risk_age: 80

environment:
  dimensions: [1000, 400]

people:
  number: 1000
  initially_infected: 8
  radius: 5 # int
  age_range: [0, 100]
  healthy:
    speed: [0.8, 1.4]
    frame_limit: [0, 0]
  infected:
    speed: [0.5, 1.5]
    frame_limit: [150, 350]
  recovered:
    speed: [0.8, 1.4]
    frame_limit: [0, 0]
  dead:
    speed: [0, 0]
    frame_limit: [100, 250]

events:
  - enable: no
    type: 'social distancing'
    frame_trigger:
      frame: 100
  - enable: no
    type: 'lockdown'
    frame_trigger:
      frame: 400
  - enable: no
    type: 'normal'
    frame_trigger:
      frame: 600

appearance:
  show:
    plot: yes
    text: no
  origins:
    simulation: [0, 0]
    plot: [20, 420]
    text: [680, 420]
  people:
    healthy_colour: [153, 153, 255]
    recovered_colour: [211, 126, 220]
    dead_colour: [50, 50, 50]
    infected_colour: [192, 99, 18]
  background:
    bg_colour: [255, 255, 255]
  text:
    font: 'arialrounded'
    size: 22
