pandemic:
  death_rate: 0.5
  frames_to_death: 1000
  frames_to_bury: 200

environment:
  dimensions: [1000, 600]

people:
  number: 100
  infected: 5
  radius: 5  # int

appearance:
  people:
    healthy_colour: [153, 153, 255]
    recovered_colour: [211, 126, 220]
    dead_colour: [50, 50, 50]
    infected_colour: [192, 99, 18]
  background:
    bg_colour: [255, 255, 255]
